In [1]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.54-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.9.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 713.8 kB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.12/site-packages (from yfinance) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2024.8.30)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.54-py2.py3-none-any.whl (108 kB)
Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.9-cp312-cp312-macosx_10_15_x86_64.whl size=273613 sha256=5adafacbea5efb092b167aeb92d098887936d443bb1ee75789043188f2a4263e
  Stored in directory: /Users/neerajsmacbook/Library/Caches/pip/wheels/43/ef/2d/2c51d496bf084945ffdf838b4cc8767b8ba1cc20eb41588831
Successfully built peewee
Installing collected packages: peewee, multitasking, yfinance
Successfully installed multitasking-0.0.11 peewee-3.17.9 yfinance-0.2.54

In [4]:
import yfinance as yf
import pandas as pd
import numpy as np

In [6]:
INDICES = ["^NSEI", "^NSEBANK", "^CNXIT", "^CNXAUTO", "^CNXFMCG", "^CNXMETAL", "^CNXREALTY", "^CNXENERGY", "^CNXMEDIA", "^CNXPSUBANK", "^BSESN"]

for i in INDICES:
    index_data = yf.download(i, start='2015-01-01', end='2024-12-31')
    
    variable_name = i.replace('^', '')

    if isinstance(index_data.columns, pd.MultiIndex):
        index_data.columns = index_data.columns.droplevel(1)

    index_data['Change_Percentage_Indices'] = index_data['Close'].pct_change() * 100
    index_data['Open'] = index_data['Open'].round(2)
    index_data['High'] = index_data['High'].round(2)
    index_data['Low'] = index_data['Low'].round(2)
    index_data['Close'] = index_data['Close'].round(2)
    index_data['Change_Percentage_Indices'] = index_data['Change_Percentage_Indices'].round(2)
    
    globals()[variable_name] = index_data
    
    
NSEI["Index_name"] = "NIFTY 50"
NSEBANK["Index_name"] = "NIFTY BANK"
CNXIT["Index_name"] = "NIFTY IT"
CNXAUTO["Index_name"] = "NIFTY AUTO"
CNXFMCG["Index_name"] = "NIFTY FMCG"
CNXMETAL["Index_name"] = "NIFTY METAL"
CNXREALTY["Index_name"] = "NIFTY REALTY"
CNXENERGY["Index_name"] = "NIFTY ENERGY"
CNXMEDIA["Index_name"] = "NIFTY MEDIA"
CNXPSUBANK["Index_name"] = "NIFTY PSU BANK"
BSESN["Index_name"] = "SENSEX"

INDICES = pd.concat([NSEI, NSEBANK, CNXIT, CNXAUTO, CNXFMCG, CNXMETAL, CNXREALTY, CNXENERGY, CNXMEDIA, CNXPSUBANK, BSESN], ignore_index=False)

INDICES = INDICES[['Index_name'] + [col for col in INDICES.columns if col != 'Index_name']]

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
#Daily Return Percentage
INDICES['Daily_Return_%'] = ((INDICES['Close'] - INDICES['Open']) / INDICES['Open']) * 100
INDICES['Daily_Return_%'] = INDICES['Daily_Return_%'].round(2)
INDICES['Daily_Return_%'] = INDICES['Daily_Return_%'].map(lambda x: f'{x:.2f}%')

INDICES['Change_Percentage_Indices'] = INDICES['Change_Percentage_Indices'].map(lambda x: f'{x:.2f}%')

#Volatility
INDICES['Volatility'] = ((INDICES['High'] - INDICES['Low']) / INDICES['Open']) * 100
INDICES['Volatility'] = INDICES['Volatility'].round(2)

In [15]:
INDICES

Price,Index_name,Close,High,Low,Open,Volume,Change_Percentage_Indices,Daily_Return_%,Volatility
Date,,,,,,,,,
2015-01-02,NIFTY 50,8395.45,8410.60,8288.70,8288.70,101900,nan%,1.29%,1.47
2015-01-05,NIFTY 50,8378.40,8445.60,8363.90,8407.95,118200,-0.20%,-0.35%,0.97
2015-01-06,NIFTY 50,8127.35,8327.85,8111.35,8325.30,172800,-3.00%,-2.38%,2.60
2015-01-07,NIFTY 50,8102.10,8151.20,8065.45,8118.65,164100,-0.31%,-0.20%,1.06
2015-01-08,NIFTY 50,8234.60,8243.50,8167.30,8191.40,143800,1.64%,0.53%,0.93
...,...,...,...,...,...,...,...,...,...
2024-12-23,SENSEX,78540.17,78918.12,78189.19,78488.64,10300,0.64%,0.07%,0.93
2024-12-24,SENSEX,78472.87,78877.36,78397.79,78707.37,6200,-0.09%,-0.30%,0.61
2024-12-26,SENSEX,78472.48,78898.37,78173.38,78557.28,5600,-0.00%,-0.11%,0.92
2024-12-27,SENSEX,78699.07,79043.15,78598.55,78607.62,7700,0.29%,0.12%,0.57
2024-12-30,SENSEX,78248.13,79092.70,78077.13,78637.58,8900,-0.57%,-0.50%,1.29

In [8]:
NSEI

Price,Close,High,Low,Open,Volume,Change_Percentage_Indices,Index_name
Date,,,,,,,
2015-01-02,8395.45,8410.60,8288.70,8288.70,101900,NaN,NIFTY 50
2015-01-05,8378.40,8445.60,8363.90,8407.95,118200,-0.20,NIFTY 50
2015-01-06,8127.35,8327.85,8111.35,8325.30,172800,-3.00,NIFTY 50
2015-01-07,8102.10,8151.20,8065.45,8118.65,164100,-0.31,NIFTY 50
2015-01-08,8234.60,8243.50,8167.30,8191.40,143800,1.64,NIFTY 50
...,...,...,...,...,...,...,...
2024-12-23,23753.45,23869.55,23647.20,23738.20,189800,0.70,NIFTY 50
2024-12-24,23727.65,23867.65,23685.15,23769.10,177700,-0.11,NIFTY 50
2024-12-26,23750.20,23854.50,23653.60,23775.80,177700,0.10,NIFTY 50
2024-12-27,23813.40,23938.85,23800.60,23801.40,176800,0.27,NIFTY 50
2024-12-30,23644.90,23915.35,23599.30,23796.90,364900,-0.71,NIFTY 50

In [17]:
INDICES.to_csv('indices.csv', index=True)